### ISSUE TITLE
Fails with unknown IO errors

### ISSUE THREAD

**Issue by Fabian42** [cjnaz/RCloneSync#18] opened 2018-05-25 20:56 UTC
When running --FirstSync, I get a lot of output over almost an hour and it ends with "Critical Error Abort - Must run --FirstSync to recover." and then "All done". Did it fail or is it done?
I also can't see what IO errors it means. It shows some duplicate file warnings, but does that really completely prevent it from working at all? Why doesn't it just call them "file.txt" and "file (1).txt"? Also there are some "can't update a google document" warnings, but that also shouldn't make it fail.
When trying the same command without "--FirstSync" (so the normal run), I get "Cannot find prior local or remote lsl files".

**Comment by cjnaz** [comment] 2018-05-25 21:15
Hi.  Read the README carefully regarding the final message.   Have a look
at the local and remote file systems to see what the state is...  what's
synced and what's not.  Turn on the verbose switch to see which files are
having a problem.

On May 25, 2018 1:56 PM, "Fabian Röling" <notifications@github.com> wrote:

When running --FirstSync, I get a lot of output over almost an hour and it
ends with "Critical Error Abort - Must run --FirstSync to recover." and
then "All done". Did it fail or is it done?
I also can't see what IO errors it means. It shows some duplicate file
warnings, but does that really completely prevent it from working at all?
Why doesn't it just call them "file.txt" and "file (1).txt"? Also there are
some "can't update a google document" warnings, but that also shouldn't
make it fail.
When trying the same command without "--FirstSync" (so the normal run), I
get "Cannot find prior local or remote lsl files".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cjnaz/RCloneSync/issues/18>, or mute the thread

**Comment by Fabian42** [comment] 2018-05-25 21:28
I can't see anything about a final message or anything where it behaves weirdly in Readme, other than "dryrun oddity".
The sync does actually happen, exactly like described in the section about FirstSync, but it gives out the error message and subsequent regular runs don't work.
I'll try the verbose output tomorrow.

**Comment by cjnaz** [comment] 2018-05-25 21:49
If there is some problem where the is a risk of deleting files it defaults
to forcing a firstsync.   See Runtime Error Handling.  Next try first sync
with verbose to see which files are having a problem.

**Comment by Fabian42** [comment] 2018-05-26 11:20
FirstSync doesn't delete anything anyway, so that shouldn't make it abort, right?
The same with --Verbose seems to give no different output than without. Also, it says "Errors: 0" all the time, but then still: "Attempt 3/3 failed with 3 errors and: not deleting files as there were IO errors"

**Comment by cjnaz** [comment] 2018-05-26 16:49
Post a portion of the verbose error log with the errors, and the command
line you are using.  What cloud service are you using?  Rclone commands
word on the command line?

On May 26, 2018 4:20 AM, "Fabian Röling" <notifications@github.com> wrote:

FirstSync doesn't delete anything anyway, so that shouldn't make it abort,
right?
The same with --Verbose seems to give no different output than without.
Also, it says "Errors: 0" all the time, but then still: "Attempt 3/3 failed
with 3 errors and: not deleting files as there were IO errors"

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cjnaz/RCloneSync/issues/18#issuecomment-392254864>, or mute
the thread

**Comment by Fabian42** [comment] 2018-05-26 19:12
I ran `--FirstSync --Verbose` and then shortened and anonymised the output.
There's a Google document containing a slash on Google Drive, maybe that could be an issue?
RClone works, as far as I've used it (setting up the cloud service) and as I said, the cloning process itself does work, but the index apparently doesn't get created that the regular sync needs.

```fabian@laptop:~$ /home/fabian/Desktop/programs/RCloneSync-master/RCloneSync.py --FirstSync --Verbose drive: /home/fabian/drive
2018-05-26 20:31:22,185/:  ***** BiDirectional Sync for Cloud Services using RClone *****
2018-05-26 20:31:22,192/:  Synching Remote path  <drive:>  with Local path  </home/fabian/drive/>
2018-05-26 20:31:22,192/:  >>>>> Generating --FirstSync Local and Remote lists
2018-05-26 20:33:17,778/:  >>>>> Generating Local and Remote lists
2018-05-26 20:34:57,613/:    LOCAL    Checking for Diffs                  - /home/fabian/drive/
2018-05-26 20:34:57,652/:    REMOTE   Checking for Diffs                  - drive:
2018-05-26 20:34:57,652/:    REMOTE     File size is different            - documents/google_docs/File_Name/Containing_Slash.xlsx
2018-05-26 20:34:57,652/:    REMOTE     File size is different            - documents/google_docs/file.xlsx
2018-05-26 20:34:57,684/:       2 file change(s) on REMOTE:    0 new,    0 newer,    0 older,    0 deleted
2018-05-26 20:34:57,684/:  >>>>> Applying changes on Remote to Local
2018-05-26 20:34:57,684/:  >>>>> Synching Local to Remote
2018/05/26 20:35:05 programs/titanium/com.keramidas.TitaniumBackupPro-721447d4e65419eb3b3c37fa79ca15e2.apk.bz2: Duplicate file detected
2018/05/26 20:35:12 todo/3/L/Folder 1/Backup/File_name.OGG: Duplicate file detected
2018/05/26 20:35:12 todo/3/L/Folder 1/Backup/File name.wav: Duplicate file detected
2018/05/26 20:35:12 todo/3/L/Folder 1/Backup/File_name 1_ogg_001.WAV: Duplicate file detected
...
2018/05/26 20:35:21 programs/folder/Folder - Name/Folder/File Name.TAK: Duplicate file detected
...
2018/05/26 20:35:58 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.4s

...
2018/05/26 20:36:48 documents/google_docs/file.xlsx: Failed to copy: can't update a google document
2018/05/26 20:36:48 documents/google_docs/file_name.xlsx: Failed to copy: can't update a google document
2018/05/26 20:36:48 documents/google_docs/File_Name/Containing_Slash.xlsx: Failed to copy: can't update a google document
2018/05/26 20:36:48 Google drive root '': Waiting for checks to finish
2018/05/26 20:36:48 Google drive root '': Waiting for transfers to finish
2018/05/26 20:36:48 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:36:48 Attempt 1/3 failed with 3 errors and: not deleting files as there were IO errors
2018/05/26 20:36:55 programs/titanium/com.keramidas.TitaniumBackupPro-721447d4e65419eb3b3c37fa79ca15e2.apk.bz2: Duplicate file detected
2018/05/26 20:36:58 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             21190
Transferred:            0
Elapsed time:      2m0.4s

...
2018/05/26 20:37:58 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             21190
Transferred:            0
Elapsed time:      3m0.4s

...
2018/05/26 20:38:11 Google drive root '': Waiting for checks to finish
2018/05/26 20:38:11 Google drive root '': Waiting for transfers to finish
2018/05/26 20:38:11 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:38:11 Attempt 2/3 failed with 3 errors and: not deleting files as there were IO errors
...
2018/05/26 20:38:58 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             42380
Transferred:            0
Elapsed time:      4m0.4s

...
2018/05/26 20:39:28 Google drive root '': Waiting for checks to finish
2018/05/26 20:39:28 Google drive root '': Waiting for transfers to finish
2018/05/26 20:39:28 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:39:28 Attempt 3/3 failed with 3 errors and: not deleting files as there were IO errors
2018/05/26 20:39:28 Failed to sync: not deleting files as there were IO errors
2018-05-26 20:39:28,027/:    WARNING  rclone sync try 0 failed.           - /home/fabian/drive/
...
2018/05/26 20:40:28 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.4s

...
2018/05/26 20:41:28 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.4s

...
2018/05/26 20:41:37 Google drive root '': Waiting for checks to finish
2018/05/26 20:41:37 Google drive root '': Waiting for transfers to finish
2018/05/26 20:41:37 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:41:37 Attempt 1/3 failed with 3 errors and: not deleting files as there were IO errors
...
2018/05/26 20:42:28 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             21190
Transferred:            0
Elapsed time:      3m0.4s

...
2018/05/26 20:43:15 Google drive root '': Waiting for checks to finish
2018/05/26 20:43:15 Google drive root '': Waiting for transfers to finish
2018/05/26 20:43:15 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:43:15 Attempt 2/3 failed with 3 errors and: not deleting files as there were IO errors
2018/05/26 20:43:24 programs/titanium/com.keramidas.TitaniumBackupPro-721447d4e65419eb3b3c37fa79ca15e2.apk.bz2: Duplicate file detected
2018/05/26 20:43:28 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             42380
Transferred:            0
Elapsed time:      4m0.4s

...
2018/05/26 20:44:28 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             42380
Transferred:            0
Elapsed time:      5m0.4s

...
2018/05/26 20:44:38 Google drive root '': Waiting for checks to finish
2018/05/26 20:44:38 Google drive root '': Waiting for transfers to finish
2018/05/26 20:44:38 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:44:38 Attempt 3/3 failed with 3 errors and: not deleting files as there were IO errors
2018/05/26 20:44:38 Failed to sync: not deleting files as there were IO errors
2018-05-26 20:44:38,582/:    WARNING  rclone sync try 1 failed.           - /home/fabian/drive/
...
2018/05/26 20:45:39 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.5s

...
2018/05/26 20:46:39 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.5s

...
2018/05/26 20:46:39 Google drive root '': Waiting for checks to finish
2018/05/26 20:46:39 Google drive root '': Waiting for transfers to finish
2018/05/26 20:46:39 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:46:39 Attempt 1/3 failed with 3 errors and: not deleting files as there were IO errors
...
2018/05/26 20:47:39 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             21189
Transferred:            0
Elapsed time:      3m0.5s

...
2018/05/26 20:48:01 Google drive root '': Waiting for checks to finish
2018/05/26 20:48:01 Google drive root '': Waiting for transfers to finish
2018/05/26 20:48:01 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:48:01 Attempt 2/3 failed with 3 errors and: not deleting files as there were IO errors
...
2018/05/26 20:48:39 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             42378
Transferred:            0
Elapsed time:      4m0.5s

...
2018/05/26 20:49:39 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             42378
Transferred:            0
Elapsed time:      5m0.5s

...
2018/05/26 20:49:40 Google drive root '': Waiting for checks to finish
2018/05/26 20:49:40 Google drive root '': Waiting for transfers to finish
2018/05/26 20:49:40 Google drive root '': not deleting files as there were IO errors
2018/05/26 20:49:40 Attempt 3/3 failed with 3 errors and: not deleting files as there were IO errors
2018/05/26 20:49:40 Failed to sync: not deleting files as there were IO errors
2018-05-26 20:49:40,853/:    WARNING  rclone sync try 2 failed.           - /home/fabian/drive/
2018-05-26 20:49:40,853/:    ERROR    rclone sync failed.  (Line 384)     - /home/fabian/drive/
2018-05-26 20:49:40,879/:  ***** Critical Error Abort - Must run --FirstSync to recover.  See README.md *****
2018-05-26 20:49:40,886/:  >>>>> All done.


fabian@laptop:~$ ```

**Comment by cjnaz** [comment] 2018-05-26 19:43
Interesting.  The File_Name/Containing_Slash.xlsx may be a corner case not
handled well. The filename may not be legal on Linux. Try changing the name
on the remote side. That doesn't explain the other google_doc file errors.

The log messages with '/' in the time stamp (2018/05/26) are from rclone,
fyi, so most all of the errors are rclone being unhappy. Look at each of
the types of errors to try to debug each, such as the Duplicate file
detected errors.  If you run rclone sync manually you should get the same
errors.  Check the rclone forums for specific issues such as the Google
docs errors.

I'm interested in the root causes so please post your findings here for
closure. So far I'm not seeing any RcloneSync issues.

**Comment by Fabian42** [comment] 2018-05-26 22:56
What I've done so far:
Renamed it, now it creates a folder with that name and the output is much shorter, not even duplicate warnings. But it still fails.
Running `rclone sync`, output shows no problems.
Running RCloneSync again and it shows the duplicate warnings again!
Running `rclone sync` again and it runs through without problems.
Running RCloneSync again and it shows the same regular output, including the duplicate file warnings.
Tomorrow I'll try deleting the duplicate files and then running RCloneSync again.

**Comment by Fabian42** [comment] 2018-05-27 19:44
Ran it again, got the very short output again.
Ran it again, got the long output again.
Deleted duplicates, ran it again, now it only has a problem with one file. I can try removing it for now (because it's owned by someone else and I have a link), but in the long run I need it.
Apparently it downloaded the Google docs as xlsx and then uploaded them again as a regular file.
Removed it and now it shows a different Google document in the errors.
Ran `rclone sync` again and it goes through without problem, so it is actually a RCloneSync problem:

```fabian@laptop:~$ cd drive
fabian@laptop:~/drive$ rclone sync drive: local:
2018/05/27 21:25:05 
Transferred:   368.940 kBytes (6.104 kBytes/s)
Errors:                 0
Checks:             10266
Transferred:            7
Elapsed time:      1m0.4s

2018/05/27 21:26:05 
Transferred:   368.940 kBytes (3.062 kBytes/s)
Errors:                 0
Checks:             17334
Transferred:            7
Elapsed time:      2m0.4s

2018/05/27 21:26:47 Local file system at /home/fabian/drive: Waiting for checks to finish
2018/05/27 21:26:47 Local file system at /home/fabian/drive: Waiting for transfers to finish
2018/05/27 21:26:47 Waiting for deletions to finish
2018/05/27 21:26:47 
Transferred:   368.940 kBytes (2.266 kBytes/s)
Errors:                 0
Checks:             21174
Transferred:            7
Elapsed time:     2m42.8s
fabian@laptop:~/drive$```

**Comment by cjnaz** [comment] 2018-06-02 15:12
The `rclone sync` you are doing above is from the remote to the local, and I see that it runs clean.  However, RCloneSync runs `rclone sync` only from the local to the remote.  Try running `rlcone sync local: drive:` to see if that runs clean.

RCloneSync only does copies of new/newer individual remote files to the local filesystem, and deletes individual files on the local filesystem that were deleted on the remote filesystem.  At this stage, the local filesystem is correct and complete.  RCloneSync finishes up by using `rclone sync local: remote:` to make the remote match the local.  rclone itself errors on anything it can't handle.  Checking the log output, if the date stamp has '/'s, those are message from rclone.

**Comment by Fabian42** [comment] 2018-06-02 17:08
I just updated RClone to beta and now RCloneSync goes through completely! But I get output like this, maybe it interests you:
2018-06-02 18:53:22,854/:  Something wrong with this line (ignored) in ```/home/fabian/.RCloneSyncWD/drive__remoteLSL:
   <       -1 2018-05-27 20:56:02.614000000 documents/google_docs/File name.docx
>```

**Comment by cjnaz** [comment] 2018-06-02 21:10
This error comes from `loadList()`.  I see that the example above shows a "-1" file size for some reason.  Any entries in the rclone lsl that cannot be parsed, as in this example with a -1 file size, are skipped.  The problem is that if they have been modified on the remote side they will be blasted back to the local copy version by the final rclone sync.  You probably want to get this issue resolved.  

- Do you have several files with this error message?  Look at the *localLSL and *remoteLSL files in the RCloneSync local working directory (localWD).
- Are they all google doc file types?  I did a quick search on the rclone forum and didn't find anything about -1 file sizes.  Hum.

File size change sync isn't a robust feature in RCloneSync.  One hack fix would be to make loadList() ignore the file size field, and eliminate the size change checks in determining which remote files to copy local.  However, if a file size changes and not the date then something very strange has happened.

fyi, I'm running rclone v1.37-157-g5a3a56ab\u03b2

**Comment by Fabian42** [comment] 2018-06-03 00:17
I tried to set it up with Cron, but now I can't even get it to work again. Firstly, Cron is a horrible system, there's a hundred things that behave differently than when running from a terminal. Secondly, sometimes rclone goes through successfully, sometimes it fails. And since logging is also a horrible mess in Cron, I can't always figure out what's happening.

My output of `rclone -v`:
```rclone v1.41-076-g2b332bceβ
- os/arch: linux/amd64
- go version: go1.10.1```
Yes, they put an actual beta in that number. Not the best of ideas in my opinion.

The biggest problem I have right now is that it all behaves inconsistently: Sometimes I get only one error, sometimes multiple, sometimes none. And it takes so long on every single run, it stole hours of my time.

Why can't Google just publish a proper Google Drive client? Or anyone? Why are there a hundred sort of working Google Drive clients, but not a single proper one? Why is Cron such a giant mess and why is there not a single alternative for it that actually works like a sane user would expect? I'll go to bed now and try again tomorrow. Yet another weekend sacrificed to dark side of Linux.

**Comment by cjnaz** [comment] 2018-06-03 04:27
I feel your pain.
rclone verbose can be quite noisy.  rclone has 3x retries on many commands.  I recommend running RCloneSync without the --Verbose or rcVerbose switches.  If rclone has a real fail then RCloneSync will get the message and log it.  Otherwise, you can ignore the rclone messages.

Here's the crontab entry I use.  It runs a sync at 15min and 45min each hour.  Any stdout and stderr output is directed to a runlog file so I can catch it for debug.

`          15,45    *       *              *                  *    /home/<me>/.RCloneSyncWD/RCloneSync.py GDrive:  /mnt/<path to head of GDrive locally> --CheckAccess >> /home/<me>/.RCloneSyncWD/GDrive_runlog 2>&1`

fyi, @hildogjr forked the project, brought it up on Python3, did a lot of work on Python and Linux style standardization, and...  added a cron setup switch.  See 
[https://github.com/hildogjr/RCloneSync/blob/master/RCloneSync.py](url)

**Comment by hildogjr** [comment] 2018-06-03 19:02
Yes, cron is better for simple tasks and provide message output from it can be quite difficult.
Despise the option, to my main folders I still running RCloneSync.py in terminal, to see the results, as @cjnaz does.
I hope that in the future, RCloneSync.py could be integrated on [RcloneBrowser](https://github.com/mmozeiko/RcloneBrowser) that could keep a icon close to the clock / task bar as the DropBox nautilus does.
I like the rclone software, because it centralize and give more options, but the GUI interface RClone Browser is stuck in development and it could be good software package to that user that are look for some replacement do Windows cloud clients.

**Comment by Fabian42** [comment] 2018-07-07 12:10
I tried again to set up RCloneSync and I get these "Failed to copy: can't update a google document" errors again. They make it fail synchronising or even creating the index. What can be done against that?

**Comment by cjnaz** [comment] 2018-07-07 17:31
Hi.  Try rclone copy from drive: to local, and vise versa.  I suspect that
this is an rclone or Google Drive limitation.  Also try the V2 rclonesync
branch and add a filter for the doc file extensions. If you can confirm
it's a Google Drive constraint check the rclone forum.
Cjn

**Comment by cjnaz** [comment] 2018-07-07 17:40
Also see https://github.com/ncw/rclone/issues/565

**Comment by cjnaz** [comment] 2018-07-08 16:39
I was suggesting [https://github.com/cjnaz/RCloneSync/tree/V2](url), but this version wont fix the problem.  I created a google doc test file online and i see that the file shows up via rclone lsl Drive: as having a size as
  -1 2018-07-08 09:12:38.890000000 This is a test doc.docx
The negative size trips up rclonesync.py.  Ill look at this later in the week.
Please do an rclone lsl of your Drive: and check that the files that are having problems have a negative size.

**Comment by Fabian42** [comment] 2018-07-08 21:43
Yes, they have size -1.
Sometimes I wonder why nobody had the problems I have before… Linux is a really common source of that wondering…

**Comment by Fabian42** [comment] 2018-07-14 15:44
Has "later this week" already happened?

**Comment by cjnaz** [comment] 2018-07-14 16:43
Being Saturday I guess so.

I was reading up about Google docs file handling on the rclone forum.  I'll
do so experimenting shortly.

**Comment by cjnaz** [comment] 2018-07-15 19:46
This is an issue with handling Google documents.  I'm closing this issue.  Refer to #22 please.

**Closed by cjnaz** 2018-07-15 19:46 UTC
